repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: ['--ini', '.bandit']
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.790'
    hooks:
      - id: mypy
        args: []
        additional_dependencies:
          - flask==1.1.2
          - feedparser==6.0.2
          - feedgen==0.9.0
          - genutility[json,http,flask]==0.0.65
          - pafy==0.5.5
          - pymongo==3.11.1
          - werkzeug==1.0.1
          - WTForms==2.3.3
          - youtube-dl==2020.12.2
