repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: mixed-line-ending
        args: ["--fix=no"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v3.3.1'
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]
  - repo: https://github.com/psf/black
    rev: '23.1.0'
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.4'
    hooks:
      - id: bandit
        args: ['--ini', '.bandit']
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.0.0'
    hooks:
      - id: mypy
        args: ["--install-types", "--non-interactive", "--show-error-codes"]
        additional_dependencies:
          - appdirs==1.4.4
          - feedgen==0.9.0
          - feedparser==6.0.10
          - flask==2.2.2
          - genutility[json,http,flask]==0.0.88
          - pafy==0.5.5
          - werkzeug==2.2.2
          - WTForms==3.0.1
          - youtube-dl==2021.12.17
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
