repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: [--fix=no]
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.10.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: 1.2.0
  hooks:
  - id: pyproject-fmt
- repo: https://github.com/asottile/pyupgrade
  rev: v3.14.0
  hooks:
  - id: pyupgrade
    args: [--py38-plus]
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
  - id: bandit
    args: [--ini, .bandit]
- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.5.1
  hooks:
  - id: mypy
    args: [--install-types, --non-interactive, --show-error-codes]
    additional_dependencies:
    - feedgen==0.9.0
    - feedparser==6.0.10
    - flask==2.3.3
    - genutility[flask,http,json]==0.0.99
    - pafy==0.5.5
    - platformdirs==3.5.0
    - werkzeug==2.3.7
    - WTForms==3.0.1
    - youtube-dl==2021.12.17
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
  hooks:
  - id: detect-secrets
