repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ["--fix=no"]
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: ['--ini', '.bandit']
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
      - id: mypy
        args: []
        additional_dependencies:
          - feedgen==0.9.0
          - feedparser==6.0.8
          - flask==2.0.1
          - genutility[json,http,flask]==0.0.74
          - pafy==0.5.5
          - werkzeug==2.0.1
          - WTForms==2.3.3
          - youtube-dl==2021.6.6
