repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.0.1'
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ["--fix=no"]
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: '21.11b1'
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.1'
    hooks:
      - id: bandit
        args: ['--ini', '.bandit']
  - repo: https://gitlab.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "--install-types", "--non-interactive"]
        additional_dependencies:
          - appdirs==1.4.4
          - feedgen==0.9.0
          - feedparser==6.0.8
          - flask==2.0.1
          - genutility[json,http,flask]==0.0.78
          - pafy==0.5.5
          - werkzeug==2.0.2
          - WTForms==3.0.0
          - youtube-dl==2021.6.6
